name: Deploy Docker Image from Docker Hub (Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Repository (Optional)
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull noredineba/imagesrepository1:latest

      - name: Stop and Remove Existing Docker Container (Windows PowerShell)
        shell: powershell
        run: |
          $container = docker ps -q -f "name=myapp1"
          if ($container) {
            docker stop myapp1
            docker rm myapp1
          }
          else {
            Write-Host "No existing container named 'myapp1' found."
          }

      - name: Run Docker Container
        run: |
          docker run -d --name myapp1 -p 4000:4000 noredineba/imagesrepository1:latest
